language: erlang
script: "git clone https://github.com/elixir-lang/elixir.git && cd elixir && make compile && cd .. && elixir/bin/elixir elixir/bin/mix do deps.get, test"
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
otp_release:
  - R15B01
  - R15B